# Generated by Django 6.1 on 2026-08-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_firstName', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_lastName', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
